name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 17 * * 1'
    - cron: '0 17 * * 3'
    - cron: '0 17 * * 5'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5b0414da0733d53119cd40df
